### ISSUE TITLE
Block on likes

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/instapy-gui#69]
Hey Felix,

somehow on one of my accounts the log outputs:` -------- WARNING! Image was NOT liked! You are have a BLOCK on likes!` Checking the image it's really not liked. 
The thing is if I manually like it works both browser and app.
Not sure if this is the right place or if I should post at instapy directly. 

Cheers

**Comment by GaWr26** [comment]
Checked the InspaPy repository and saw this seems to be due to a change in IG UI and seems fixed in InstaPy 0.5.5.
Just need to know how to update with the current InstaPy GUI setup.

Cheers

**Comment by breuerfelix** [comment]
sorry for the late reply but this is NOT fixed right now.

Currently I am preparing some changes to instapy which should fix this issue but this is in testing phase right now :)

alot of instapy users got these problems.

there are some other errors I am curly fixing in instapy and if they are in instapy master they are also in InstaPy gui, you just have to delete the env folder and run over the setup.sh or setup.bat file again.

I will let you know once the minor fixes are out, but the block fix will need some more testing :)

**Comment by GaWr26** [comment]
Thanks Felix, really appreciate your work!

**Comment by breuerfelix** [comment]
glad to hear that :)

so you can delete env folder and go through setup.bat again.

This wont fix your block problem but it will fix some other issues and MAYBE also the block problem.

**Comment by GaWr26** [comment]
Thanks for the quick reply. 
I updated and now when I start the bot I get this on the RaspberryPi:

```
received message: {"handler":"status"}
Traceback (most recent call last):
  File "bot.py", line 10, in <module>
    from instapy import InstaPy, set_workspace
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/instapy/instapy.py", line 26, in <module>
    from .clarifai_util import check_image
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/clarifai/rest/client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/clarifai/rest/grpc/proto/clarifai/api/endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/InstaPyGUI/env/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-arm-linux-gnueabihf.so)
```

trying to update LibC I get this: `libc6 ist schon die neueste Version (2.24-11+deb9u4).`

**Comment by breuerfelix** [comment]
wow someone else got the same problem, with another package on the pi right now... seems like there is some problem going on right now! I will check that on my pi now :)

**Comment by GaWr26** [comment]
Hey Felix, any updates on this issue? Did you get it working on your pi? i have three bots in three different virtual environments and one of them does work. Really strange.

**Comment by breuerfelix** [comment]
currently we are having some trouble with the blocks thats why I am developing the core right now, and we will switch to firefox soon. firefox also works on rpi if you use the raspbian buster image (the new one). once this is updated I will update the gui and I hopefully can continue programming the gui :)

**Comment by GaWr26** [comment]
Hey Felix, any updates from your side? Did you find a way to keep using the bot without getting blocked? Is there a current status documented somewhere? I'm currently experimenting with jarvee and get the blocks there as well. Running from my residential home IP...

Cheers

**Comment by breuerfelix** [comment]
yes we are currently making a huge improvement towards this :)

https://github.com/timgrossmann/InstaPy/pull/4759

if you have a look at this 0.6.0 version, we switched to firefox with an anti selenium extension :) we also now use a mobile user agent.

when this gets merged into instapy, instapy-gui will also get updated :)

**Comment by GaWr26** [comment]
That's great news, you guys rock! Apparently you're the first to find a fix for the new challenges.

Will this work on Raspberry Pi? I will give it a try once I find the time tomorrow.

**Comment by GaWr26** [comment]
Hey Felix, I was so curious and just tried your PR on my Raspberry Pi and get this:
```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "bot.py", line 24, in <module>
    session = InstaPy(username=insta_username, password=insta_password, multi_logs=True, disable_image_load=True, headless_browser=True, split_db=True)
  File "/home/pi/InstaPy/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/pi/InstaPy/instapy/browser.py", line 108, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/InstaPy/assets/geckodriver'
```
Not sure if I'm missing something or it's just not ready...

**Comment by breuerfelix** [comment]
you need to download another GeckoDriver :) somehow the latest one isnt available for arm processors...

you have to download 0.23.0 here https://github.com/mozilla/geckodriver/releases for arm.

if you downloaded it, put the path to the binary in the instapy constructor as argument called `geckodriver_path`, tell me if that worked !

**Comment by GaWr26** [comment]
Looks like I'm back in business! Thank you so much for all the support!
```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-06 16:51:51] [xxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-06 16:51:51] [xxx]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-06 16:51:57] [xxx]  - Internet Connection Status: ok
INFO [2019-08-06 16:51:57] [xxx]  -- Connection Checklist [2/3] (Hide Selenium Extension)
INFO [2019-08-06 16:51:57] [xxx]  - window.navigator.webdriver response: False
INFO [2019-08-06 16:51:57] [xxx]  - Hide Selenium Extension: ok
INFO [2019-08-06 16:51:57] [xxx]  -- Connection Checklist [3/3] (Instagram Server Status)
INFO [2019-08-06 16:52:11] [xxx]  - Instagram WebSite Status:  
INFO [2019-08-06 16:52:11] [xxx]  - Instagram Response Time:  
INFO [2019-08-06 16:52:11] [xxx]  - Instagram Reponse Code: 
INFO [2019-08-06 16:52:11] [xxx]  - Instagram Server Status: ok

................................................................
INFO [2019-08-06 16:52:34] [xxx]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-08-06 16:52:34] [xxx]  Saving account progress...

______________________________________________________________________________
INFO [2019-08-06 16:53:33] [xxx]  Starting to follow user `Followers`..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
```
One more question though. Is the new syntax documented somewhere?
I had to disable set_quote_supervisor and unfollow_users.

**Comment by GaWr26** [comment]
`follow_user_follows` unfortunately does not work. 

```
INFO [2019-08-06 17:07:43] [xxx]  User 'xxx' [1/4]
Traceback (most recent call last):
  File "bot.py", line 96, in <module>
    session.follow_user_followers(['xxx', 'xxx', 'xxx', 'xxx'], amount=35, randomize=True, sleep_delay=100)
  File "/home/pi/InstaPy/instapy/instapy.py", line 3438, in follow_user_followers
    self.logfolder,
  File "/home/pi/InstaPy/instapy/unfollow_util.py", line 1171, in get_given_user_followers
    logfolder,
  File "/home/pi/InstaPy/instapy/unfollow_util.py", line 874, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //body/div[3]/div/div[2]
```

`like_by_tags` does work though.

**Comment by breuerfelix** [comment]
haha no problem mate ! well the syntax changes are documented in the pull request :)

these function are not removed, just the signature changed (because of the Gui) so after we merged 0.6.0, instapy Gui uses the normal instapy package and not some branch anymore :)

we switched to the mobile version also, thats why alot of xpaths doesn't work. we are currently fixing all of them, be aware of daily updates :)

**Comment by GaWr26** [comment]
Good morning Felix, not sure if this is the right place to discuss 0.6.0 issues. If there's a better place please let me know. 

In general it looks really good and seems to work(no blocks so far, running very low settings) but my session crashes in less then an hour on my Raspberry Pi. It crashes so bad, that the Raspberry freezes and becomes unresponsive. No more ssh or VNC access. I have to reset the power to boot back up again. The console output looks normal and doesn't report any issues.
Any idea why this is happening? 

Also running multiple instances doesn't work. I start the first bot and it runs. Trying to start a second one, firefox crashes before it can load a page. 
The first instance isn't affected by the crash of the second one.

**Comment by GaWr26** [comment]
Update: the bot did actually continue. It was frozen for 15 minutes and did come back...
During this time I could not access the pi via ssh nor vnc...
```
INFO [2019-08-08 09:06:46] [xxx]  User: 'xxx'  |> followers: 6675  |> following: 650  |> relationship ratio: 10.26
INFO [2019-08-08 09:19:58] [xxx]  --> Already following 'xxx'!
```

**Comment by GaWr26** [comment]
I started posting my findings here: https://github.com/timgrossmann/InstaPy/issues/4823

Let's close this issue before it starts getting to messy.

**Comment by breuerfelix** [comment]
Thanks for your feedback for real ! this feedback helps a lot :)

I am currently really busy with work thats why I wasn't able to respond you but I will be active in some weeks again (finally have some vacation after that week).

Glad you posted it on the official InstaPy so converge could also have a look at those changes :)

keep up your feedback !
